# Generated by Django 5.2.16 on 2026-07-23 14:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("handle", models.CharField(max_length=40)),
                ("auth_provider", models.CharField(default="guest", max_length=16)),
                (
                    "external_user_id",
                    models.CharField(blank=True, max_length=190, null=True),
                ),
                ("xp", models.IntegerField(default=0)),
                ("level", models.IntegerField(default=1)),
                ("streak_count", models.IntegerField(default=0)),
                ("streak_shields", models.IntegerField(default=0)),
                ("streak_last_date", models.DateField(blank=True, null=True)),
                ("completed_sets", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                (
                    "description",
                    models.CharField(blank=True, max_length=140, null=True),
                ),
                ("polyline", models.TextField()),
                ("distance_m", models.IntegerField()),
                ("elevation_gain_m", models.IntegerField(default=0)),
                ("elevation_profile", models.JSONField(blank=True, null=True)),
                ("difficulty", models.CharField(max_length=12)),
                ("status", models.CharField(default="published", max_length=12)),
                ("run_count", models.IntegerField(default=0)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routes",
                        to="api.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GemDrop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("gem_id", models.UUIDField()),
                ("rarity", models.CharField(max_length=12)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("position_along_route_m", models.IntegerField()),
                ("respawn_rule", models.CharField(max_length=16)),
                ("placed_by", models.CharField(default="creator", max_length=12)),
                ("active", models.BooleanField(default=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gem_drops",
                        to="api.route",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=64)),
                ("started_at", models.DateTimeField()),
                ("duration_s", models.IntegerField(default=0)),
                ("distance_m", models.IntegerField(default=0)),
                ("pace_s_per_km", models.IntegerField(default=0)),
                ("is_walk", models.BooleanField(default=False)),
                ("status", models.CharField(default="pending", max_length=12)),
                ("xp_earned", models.IntegerField(default=0)),
                ("verdict", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="api.profile",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="api.route",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StashItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("gem_id", models.UUIDField()),
                ("collected_at", models.DateTimeField()),
                ("is_first_find", models.BooleanField(default=False)),
                (
                    "gem_drop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to="api.gemdrop",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stash",
                        to="api.profile",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.run",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="api.profile",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="run",
            constraint=models.UniqueConstraint(
                fields=("profile", "idempotency_key"), name="uniq_run_idempotency"
            ),
        ),
    ]
