# Generated by Django 5.2.16 on 2026-07-23 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gemdrop",
            name="dropped_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drops",
                to="api.profile",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="wallet",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="profile",
            name="wallet_minted",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="gemdrop",
            name="route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gem_drops",
                to="api.route",
            ),
        ),
    ]
