# Generated by Django 5.2.16 on 2026-07-27 03:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_gemdrop_dropped_by_profile_wallet_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaimAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source", models.CharField(max_length=12)),
                ("outcome", models.CharField(max_length=16)),
                ("closest_m", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gem_drop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_attempts",
                        to="api.gemdrop",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_attempts",
                        to="api.profile",
                    ),
                ),
            ],
        ),
    ]
