# Generated by Django 5.2.16 on 2026-07-28 11:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_claimattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="gemdrop",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
