# Generated by Django 5.2.16 on 2026-07-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_gemdrop_created_at"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="gemdrop",
            index=models.Index(
                fields=["active", "lat", "lng"], name="gemdrop_active_lat_lng"
            ),
        ),
    ]
