# Generated by Django 5.2.16 on 2026-07-30 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_friendship"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="wallet",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="wallet_minted",
        ),
        migrations.AddField(
            model_name="stashitem",
            name="dropped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stashitem",
            name="source",
            field=models.CharField(default="run", max_length=12),
        ),
        migrations.AlterField(
            model_name="stashitem",
            name="gem_drop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collections",
                to="api.gemdrop",
            ),
        ),
    ]
