# Generated by Django 5.2.17 on 2026-08-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_profile_wallet_remove_profile_wallet_minted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="utc_offset_minutes",
            field=models.IntegerField(default=0),
        ),
    ]
