# Generated by Django 5.2.17 on 2026-08-13 20:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_profile_utc_offset_minutes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zone",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("day", models.IntegerField()),
                ("name", models.CharField(max_length=80)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("radius_m", models.FloatField()),
                ("ring", models.JSONField(blank=True, null=True)),
                ("source", models.CharField(default="server", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["day", "lat", "lng"], name="zone_day_lat_lng")
                ],
            },
        ),
        migrations.CreateModel(
            name="MintedCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("card_uuid", models.UUIDField()),
                ("card_id", models.UUIDField()),
                ("name", models.CharField(max_length=60)),
                ("card_type", models.CharField(max_length=12)),
                ("rarity", models.CharField(max_length=12)),
                ("zone_id", models.UUIDField()),
                ("zone_name", models.CharField(max_length=80)),
                ("day", models.IntegerField()),
                ("minted_at", models.DateTimeField()),
                ("serial", models.IntegerField(default=0)),
                ("seed", models.CharField(max_length=24)),
                ("distance_m", models.IntegerField(default=0)),
                ("steps", models.IntegerField(default=0)),
                ("xp_earned", models.IntegerField(default=0)),
                ("pace_s_per_km", models.IntegerField(blank=True, null=True)),
                ("minted_during_run", models.BooleanField(default=False)),
                ("zone_known", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="api.profile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["profile", "zone_id", "day"],
                        name="card_profile_zone_day",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "card_uuid"), name="uniq_profile_card"
                    )
                ],
            },
        ),
    ]
